- hosts: switches
  gather_facts: no
  roles:
    - ../roles/ansible-pyats
  tasks:
    - name: 1. show version 커맨드 결과값 가져오기 (Get the output of the command "show version")
      pyats_parse_command:
        command: show version
      register: version_output

    - name: 2. 파싱된 커맨드 아웃풋 보여주기 (Print out the variable version_output)
      debug:
        msg:
          - "{{version_output.structured}}"

    - name: 3. 스위치 정보 보여주기 - Hostname, Version, Serial Number, Uptime (Display Switch Information - Hostname, Version, Serial Number, Uptime)
      debug:
        msg:
          - "Hostname: {{ version_output.structured.version.hostname }}"
          - "Version: {{ version_output.structured.version.version }}"
          - "Serial Number: {{ version_output.structured.version.chassis_sn }}"
          - "Uptime: {{ version_output.structured.version.uptime }}"

    - name: 4. show processes cpu 커맨드 결과값 가져오기 (Get the output of the commad "show processes cpu")
      pyats_parse_command:
        command: show processes cpu
      register: cpu_output


    - name: 5. CPU 5분 평균 사용률 보여주기 (Print out the average cpu usage(5 minutes))
      debug:
        msg:
          - "CPU: {{ cpu_output.structured.five_min_cpu }}%"
          
