- hosts: switches
  gather_facts: no
  roles:
    - ../roles/ansible-pyats
  tasks:
    - name: 1. show interfaces 커맨드 결과값 가져오기 (Get the output of the command "show interfaces")
      pyats_parse_command:
        command: show interfaces
      register: interface_output

    - name: 2. 파싱된 커맨드 아웃풋 보여주기 (Print out the variable interface_output)
      debug: 
        msg: "{{ interface_output.structured }}"

    - name: 3. GigabitEthernet 인터페이스만 저장하기 (Save the Interfaces which name contains 'GigabitEthernet' in the variable "ethernet_interface_list")
      set_fact:
        ethernet_interface_list: "{{ interface_output | json_query('structured.[*][0][?type == `Gigabit Ethernet`]') }}"

    - name: 4. GigabitEthernet 인터페이스만 보여주기 (Show the vairable "ethernet_interface_list")
      debug: 
        msg: "{{ ethernet_interface_list }}"

    - name: 5. !!MISSION!! GigabitEthernet 인터페이스 중 mtu가 1500인 인터페이스 저장하기 (Save the interfaces which has mtu 1500 in the variable "mtu_1500_ethernet_interface_list")
      set_fact:
        mtu_1500_ethernet_interface_list: "{{ ethernet_interface_list | !!MISSION!! )}}"

    - name: 6. GigabitEthernet 인터페이스 중 mtu가 1500인 인터페이스 저장하기 (Show the vairable "mtu_1500_ethernet_interface_list)
      debug: 
        msg: "{{ mtu_1500_ethernet_interface_list }}"

    - name: 7. 총 인터페이스 수 & mtu 1500인 인터페이스 수 보여주기 (Print out the total number of Interfaces & mtu 1500 interfaces)
      debug: 
        msg:    
          - "Total number of Interfaces : {{ ethernet_interface_list | length }}"         
          - "Total number of Interfaces mtu 1500 : {{ mtu_1500_ethernet_interface_list | length }}"
